### ISSUE TITLE
Missing build from #4?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/r-languageserver-feedstock#5]
It looks like not all of the builds from #4 completed:

https://github.com/conda-forge/r-languageserver-feedstock/runs/525171398

Maybe just a rekick is in order?

motivation: looking to pin on this version for a bug-fix on https://github.com/conda-forge/staged-recipes/pull/11280#discussion_r407234227

**Comment by cbrueffer** [comment]
Fixed, thanks for the notice!
